### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by OGXirvin** [giacomo-b/reddit-compilation-maker#3]
These are the errors that I get, can someone maybe help me fix it? (I ran it in CMD)

C:\Users\Xander>python C:\Users\Xander\RedditCompiler/main.py

Initializing downloads for topic GTA...

python: can't open file 'C:\Users\Xander\bulk-downloader-for-reddit\script.py': [Errno 2] No such file or directory

Initializing YouTube postprocessing for topic GTA...

Traceback (most recent call last):
  File "C:\Users\Xander\RedditCompiler\main.py", line 28, in <module>
    videos = find_valid_mp4_videos(topic["subreddits"], dirname=DOWNLOAD_DIR)
  File "C:\Users\Xander\RedditCompiler\videoUtils.py", line 47, in find_valid_mp4_videos
    for filename in os.listdir(os.path.join(dirname, sub["name"])):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'downloads\\gtaonline'

**Comment by giacomo-b** [comment]
Hey @OGXirvin can you try to run `python main.py` from within _C:\Users\Xander\RedditCompiler_?

Looks like there's a folder named _RedditCompiler_ and one named _bulk-downloader-for-reddit_.

**Comment by OGXirvin** [comment]
> 

HI I double click main.py if thats what you mean but the console closes in on me. And what do you mean by theres folders name RedditCompiler and bulk-downloader-for-reddit? Am I suppose to do something about that?
